### ISSUE TITLE
Missing LICENCE and CONTRIBUTING files

### ISSUE THREAD

**Issue by ncme** [lsinfo3/BDD-mininet#3]
Hey guys,
you are currently missing a LICENCE on this project, which means you are [accepting the default rules set by github](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license).
As a student working with a university project on sdn controllers it would be great for us if you could include an open licence that would allow us to use this work for our research.  
Also for contributing pull requests to issues, it would be great if you had a CONTRIBUTING file outlining some guidelines. 

Thanks,
Niko - Student at Universität Bremen

**Comment by JayBeeCee** [comment]
Thanks for your message. We added a LICENSE file.
Feel free to send pull requests.
